// Turn a source image into the site's WebP assets at the sizes the markup expects.
//
//   node scripts/optimize-asset.mjs <source> <basename> [--preset material|hero|social] [--force]
//
// <source> is a local file path or an https URL, so this works for images
// exported from ChatGPT, supplied by the client, or generated by an API.
// <basename> is kebab-case with no extension.
//
// Presets match the dimensions already used in scripts/build.mjs, so imported
// assets drop into existing markup without touching width/height:
//
//   material  1280x960 + 800x600          material and service page images
//   hero      1600x900 + 900x506 mobile   full-bleed hero art
//   social    1200x675, no mobile         the og:image
//
// By default, material images are cropped with Sharp's attention strategy. Use
// --fit contain to preserve an already-accurate legacy image inside the 4:3
// canvas with a controlled background instead of forcing a crop.

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import sharp from "sharp";

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const assets = join(root, "assets");

const PRESETS = {
  material: [
    { suffix: "-1280", width: 1280, height: 960 },
    { suffix: "-800", width: 800, height: 600 }
  ],
  hero: [
    { suffix: "-1600", width: 1600, height: 900 },
    { suffix: "-mobile", width: 900, height: 506 }
  ],
  social: [{ suffix: "", width: 1200, height: 675 }]
};

// Accept both "--preset hero" and "--preset=hero".
const argv = process.argv.slice(2);
const positional = [];
let presetName = "material";
let force = false;
let quality = 78;
let fit = "cover";
let background = "#f1ede4";
let position = "attention";

for (let i = 0; i < argv.length; i++) {
  const a = argv[i];
  if (a === "--force") { force = true; continue; }
  if (a.startsWith("--preset")) {
    presetName = a.includes("=") ? a.split("=")[1] : argv[++i];
    continue;
  }
  if (a.startsWith("--quality")) {
    quality = Number(a.includes("=") ? a.split("=")[1] : argv[++i]);
    continue;
  }
  if (a.startsWith("--fit")) {
    fit = a.includes("=") ? a.split("=")[1] : argv[++i];
    continue;
  }
  if (a.startsWith("--background")) {
    background = a.includes("=") ? a.split("=")[1] : argv[++i];
    continue;
  }
  if (a.startsWith("--position")) {
    position = a.includes("=") ? a.split("=")[1] : argv[++i];
    continue;
  }
  if (a.startsWith("--")) { console.error(`unknown flag ${a}`); process.exit(1); }
  positional.push(a);
}

const [source, basename] = positional;

if (!Number.isFinite(quality) || quality < 1 || quality > 100) {
  console.error(`--quality must be 1-100, got "${quality}"`);
  process.exit(1);
}

if (!source || !basename) {
  console.error("usage: node scripts/optimize-asset.mjs <source> <basename> [--preset material|hero|social] [--quality N] [--fit cover|contain] [--background #rrggbb] [--position attention|centre|north|south|east|west|northeast|northwest|southeast|southwest] [--force]");
  process.exit(1);
}
if (!/^[a-z0-9-]+$/.test(basename)) {
  console.error(`basename must be kebab-case a-z0-9-, got "${basename}"`);
  process.exit(1);
}
const preset = PRESETS[presetName];
if (!preset) {
  console.error(`unknown preset "${presetName}". Use one of: ${Object.keys(PRESETS).join(", ")}`);
  process.exit(1);
}
if (!["cover", "contain"].includes(fit)) {
  console.error(`--fit must be "cover" or "contain", got "${fit}"`);
  process.exit(1);
}

const positionMap = {
  attention: sharp.strategy.attention,
  centre: "centre",
  center: "centre",
  north: "north",
  south: "south",
  east: "east",
  west: "west",
  northeast: "northeast",
  northwest: "northwest",
  southeast: "southeast",
  southwest: "southwest"
};
const resizePosition = positionMap[position];
if (!resizePosition) {
  console.error(`unsupported --position "${position}"`);
  process.exit(1);
}

async function load(src) {
  if (/^https?:\/\//.test(src)) {
    const res = await fetch(src);
    if (!res.ok) throw new Error(`download failed: ${res.status} ${res.statusText}`);
    return Buffer.from(await res.arrayBuffer());
  }
  if (!existsSync(src)) throw new Error(`no such file: ${src}`);
  return readFileSync(src);
}

const input = await load(source);
const meta = await sharp(input).metadata();
console.log(`source: ${meta.width}x${meta.height} ${meta.format}, ${(input.length / 1024).toFixed(0)} KB\n`);

mkdirSync(assets, { recursive: true });

for (const { suffix, width, height } of preset) {
  const name = `${basename}${suffix}.webp`;
  const target = join(assets, name);
  if (existsSync(target) && !force) {
    console.log(`skip   ${name} (exists, pass --force to overwrite)`);
    continue;
  }
  if (meta.width < width) {
    console.log(`note   ${name}: source is only ${meta.width}px wide, upscaling to ${width}px will look soft`);
  }
  const out = await sharp(input)
    .resize(width, height, { fit, position: resizePosition, background })
    .webp({ quality, effort: 6 })
    .toBuffer();
  writeFileSync(target, out);
  const kb = out.length / 1024;
  console.log(
    `wrote  ${name.padEnd(40)} ${width}x${height}  ${kb.toFixed(1)} KB` +
      (kb > 180 ? `  (heavy - retry with --quality ${Math.max(55, quality - 12)})` : "")
  );
}

const main = preset[0];
console.log(`\nmarkup: width="${main.width}" height="${main.height}"`);
